#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ADDON_DIR="$ROOT_DIR/AutoDefineAddon"
BUILD_DIR="$ROOT_DIR/build"
WORKING_ADDON_DIR="$BUILD_DIR/AutoDefineAddon"
DIST_DIR="$ROOT_DIR/dist"
ZIP_NAME="AutoDefineAddon.zip"

if [[ ! -d "$ADDON_DIR" ]]; then
  echo "Add-on directory '$ADDON_DIR' not found" >&2
  exit 1
fi

# Prepare a clean build directory and copy the sources there so the
# working tree is left untouched.
rm -rf "$BUILD_DIR"
mkdir -p "$WORKING_ADDON_DIR"
cp -a "$ADDON_DIR/." "$WORKING_ADDON_DIR"

# Remove Python cache folders inside the build copy.
find "$WORKING_ADDON_DIR" -type d -name '__pycache__' -prune -exec rm -rf {} +

# Remove meta.json generated by Anki in the build copy.
if [[ -f "$WORKING_ADDON_DIR/meta.json" ]]; then
  rm "$WORKING_ADDON_DIR/meta.json"
fi

mkdir -p "$DIST_DIR"
rm -f "$DIST_DIR/$ZIP_NAME"

(
  cd "$WORKING_ADDON_DIR"
  zip -r "$DIST_DIR/$ZIP_NAME" . -x '*.DS_Store'
)

echo "Add-on packaged at $DIST_DIR/$ZIP_NAME"
