#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ADDON_DIR="$ROOT_DIR/AutoDefineAddon"
DIST_DIR="$ROOT_DIR/dist"
ZIP_NAME="AutoDefineAddon.zip"

if [[ ! -d "$ADDON_DIR" ]]; then
  echo "Add-on directory '$ADDON_DIR' not found" >&2
  exit 1
fi

# Remove Python cache folders.
find "$ADDON_DIR" -type d -name '__pycache__' -prune -exec rm -rf {} +

# Remove meta.json generated by Anki.
if [[ -f "$ADDON_DIR/meta.json" ]]; then
  rm "$ADDON_DIR/meta.json"
fi

mkdir -p "$DIST_DIR"
rm -f "$DIST_DIR/$ZIP_NAME"

(
  cd "$ADDON_DIR"
  zip -r "$DIST_DIR/$ZIP_NAME" . -x '*.DS_Store'
)

echo "Add-on packaged at $DIST_DIR/$ZIP_NAME"
